server:
  #默认配置中心的端口是8888
  port: 12000
spring:
  application:
    name: tensquare-config #服务名
    #MQ配置
  rabbitmq:
    host: 192.168.119.10
  cloud:
    config:
      server:
        #Git远程仓库
        git:
          uri: https://github.com/Flynn-fuxin/tensquare.git
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    #Eureka服务的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    #用于表示在猜测主机名时，服务器的IP地址应该与操作系统报告的主机名相对应。(注册服务和客户端如果在一台机器上则无需配置)
    prefer-ip-address: true
