server:
  #服务端口
  port: 9006
spring:
  application:
    #指定服务名
    name: tensquare-spit
  redis:
    # 主机地址
    host: 192.168.119.10
  #数据源配置
  data:
    mongodb:
      # 主机地址
      host: 192.168.119.10
      # 数据库
      database: flynn
      # 默认端口是27017
      port: 27017
eureka:
  client:
    #Eureka服务的地址
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    #用于表示在猜测主机名时，服务器的IP地址应该与操作系统报告的主机名相对应。(注册服务和客户端如果在一台机器上则无需配置)
    prefer-ip-address: true
