server:
  port: 9012
spring:
  application:
    name: tensquare-web #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
zuul:
  #添加主机的头信息
  add-host-header: true
  #敏感词设置为null
  sensitive-headers: "Authorization"
  #路由定义
  routes:
    #可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
    tensquare-base: /base/**
      #基础
      #想要映射到的路径，配置请求URL的请求规则
      #      path: /base/**
    #Eureka中的serviceId,指定Eureka注册中心中的服务id
    #      serviceId: tensquare-base #指定Eureka注册中心中的服务id
    tensquare-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: tensquare-article #指定Eureka注册中心中的服务id
    tensquare-gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: tensquare-gathering #指定Eureka注册中心中的服务id
    tensquare-friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: tensquare-friend #指定Eureka注册中心中的服务id
    tensquare-qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: tensquare-qa #指定Eureka注册中心中的服务id
    tensquare-recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: tensquare-recruit #指定Eureka注册中心中的服务id
    tensquare-spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: tensquare-spit #指定Eureka注册中心中的服务id
    tensquare-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: tensquare-user #指定Eureka注册中心中的服务id
    tensquare-search: #用户
      path: /search/** #配置请求URL的请求规则
      serviceId: tensquare-search #指定Eureka注册中心中的服务id


#    配置ribbon负载均衡
#要调用的微服务的名字
tensquare-base:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询（默认）
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
